import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, Download, FileCheck2 } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { StorePageTracker } from '@/components/store-page-tracker'

const siteUrl = 'https://www.planet-x.co'
export const metadata: Metadata = { title: { absolute: 'Free Resources for Indie Developers | planet.X' }, description: 'Free planet.X checklists and practical resources for shipping software, extensions, and digital products.', alternates: { canonical: '/store/free' }, openGraph: { title: 'Free Resources for Indie Developers | planet.X', description: 'Practical free resources from planet.X.', url: '/store/free', siteName: 'planet.X', type: 'website', images: ['/opengraph-image'] }, twitter: { card: 'summary_large_image', title: 'Free Resources for Indie Developers | planet.X', description: 'Practical free resources from planet.X.', images: ['/opengraph-image'] } }
export default function FreeResourcesPage() {
  const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'planet.X', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Store', item: `${siteUrl}/store` }, { '@type': 'ListItem', position: 3, name: 'Free Resources', item: `${siteUrl}/store/free` }] }
  return <div className="min-h-screen bg-[#030305] text-white"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /><StorePageTracker event="category_view" properties={{ category: 'Free Resources', category_slug: 'free' }} /><SiteHeader /><main><section className="border-b border-white/10 bg-white/[.018]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="font-mono text-[10px] font-bold tracking-[.18em] text-cyan-300 uppercase">Free resources</p><h1 className="mt-3 text-4xl font-bold tracking-[-.045em] sm:text-5xl">Useful before you buy anything.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/60">Free planet.X resources are meant to solve a real piece of the shipping workflow on their own. No fake value wall, no empty PDF, and no checkout required.</p></div></section><section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><article className="grid gap-7 rounded-2xl border border-white/10 bg-white/[.03] p-6 md:grid-cols-[auto_1fr_auto] md:items-center"><div className="flex size-14 items-center justify-center rounded-xl border border-cyan-300/20 bg-cyan-300/[.06]"><FileCheck2 className="size-6 text-cyan-300" aria-hidden="true" /></div><div><p className="font-mono text-[9px] font-bold tracking-[.15em] text-primary uppercase">Markdown + on-page version</p><h2 className="mt-2 text-2xl font-bold">Indie Extension Release Checklist</h2><p className="mt-3 text-sm leading-6 text-white/55">Packaging, permission review, privacy, Chrome Web Store assets, clean-profile QA, reviewer notes, and release evidence in one reusable pass.</p></div><Link href="/store/free/indie-extension-release-checklist" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3 font-mono text-[10px] font-bold tracking-[.12em] uppercase"><Download className="size-4" aria-hidden="true" /> Open checklist <ArrowRight className="size-4" aria-hidden="true" /></Link></article></section></main><SiteFooter /></div>
}
