import type { Metadata } from 'next'
import Link from 'next/link'
import { Layers3 } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { StorePageTracker } from '@/components/store-page-tracker'
import { StoreTrackedLink } from '@/components/store-tracked-link'
import { getProductById, productPath } from '@/lib/store-catalog'

export const metadata: Metadata = { title: { absolute: 'planet.X Store Bundles — Pricing Review Preview' }, description: 'Proposed planet.X and Xupply product stacks. Bundle pricing and savings are not published until owner approval.', alternates: { canonical: '/store/bundles' }, robots: { index: false, follow: true } }
const bundles = [
  { id: 'extension-launch-stack', name: 'Extension Launch Stack', description: 'A practical release stack for extension launch planning, store-ready visuals, and interface production.', products: ['indie-launch-kit', 'creator-asset-forge', 'interface-hud-kit'] },
  { id: 'developer-visual-stack', name: 'Developer Visual Stack', description: 'Reusable interface, web-atmosphere, and visual-backdrop assets for technical product presentation.', products: ['interface-hud-kit', 'website-atmosphere-pack', 'digital-worlds-wallpapers'] },
  { id: 'creator-video-stack', name: 'Creator Video Stack', description: 'Editable overlays, broadcast scenes, and glitch motion/audio assets for creator production.', products: ['creator-editing-overlays', 'creator-stream-pack', 'digital-glitch-fx'] },
  { id: 'audio-identity-stack', name: 'Audio Identity Stack', description: 'UI feedback, transitions, impacts, glitches, and short-form production sound assets.', products: ['essential-ui-sounds', 'producer-transitions-impacts', 'digital-glitch-fx'] },
]
function moneyTotal(ids: string[]) { const cents = ids.reduce((sum, id) => { const product = getProductById(id); const value = product?.price.match(/\$([0-9]+(?:\.[0-9]{1,2})?)/)?.[1]; return sum + (value ? Math.round(Number(value) * 100) : 0) }, 0); return `$${(cents / 100).toFixed(2)}` }
export default function BundlesPage() {
  return <div className="min-h-screen bg-[#030305] text-white"><StorePageTracker event="bundle_view" properties={{ surface: 'bundle_index', bundle_count: bundles.length }} /><SiteHeader /><main><section className="border-b border-white/10 bg-white/[.018]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p className="font-mono text-[10px] font-bold tracking-[.18em] text-primary uppercase">Pricing review preview</p><h1 className="mt-3 text-4xl font-bold tracking-[-.045em] sm:text-5xl">Product stacks are mapped. Bundle pricing is not.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/60">These combinations are visible for information architecture and cross-sell review. Individual current prices are shown only to establish the existing total. No bundle discount, savings claim, urgency, or bundle checkout is published until the owner approves the commercial decision.</p></div></section><section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><div className="grid gap-6 md:grid-cols-2">{bundles.map((bundle) => { const products = bundle.products.map((id) => getProductById(id)).filter((item) => item !== null); return <article key={bundle.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-6"><Layers3 className="size-5 text-cyan-300" aria-hidden="true" /><h2 className="mt-5 text-2xl font-bold">{bundle.name}</h2><p className="mt-3 text-sm leading-6 text-white/55">{bundle.description}</p><div className="mt-5 rounded-xl border border-white/10 bg-black/25 p-4"><p className="font-mono text-[9px] tracking-[.14em] text-white/35 uppercase">Current individual total</p><p className="mt-1 font-mono text-xl font-bold text-primary">{moneyTotal(bundle.products)}</p><p className="mt-1 text-xs text-white/40">Bundle price: owner approval required</p></div><ul className="mt-5 divide-y divide-white/10 border-y border-white/10">{products.map((product) => <li key={product.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{product.name}</p><p className="mt-1 text-xs text-white/45">{product.price} · {product.productType}</p></div><StoreTrackedLink href={productPath(product)} event="bundle_cta_click" properties={{ bundle_id: bundle.id, product_id: product.id }} className="font-mono text-[10px] font-bold tracking-[.1em] text-cyan-300 uppercase hover:text-white">View →</StoreTrackedLink></li>)}</ul></article> })}</div><div className="mt-10"><Link href="/store" className="font-mono text-[10px] font-bold tracking-[.12em] text-primary uppercase">← Back to store</Link></div></section></main><SiteFooter /></div>
}
