import type { Metadata } from 'next'
import Link from 'next/link'
import { Check } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { StorePageTracker } from '@/components/store-page-tracker'

const siteUrl = 'https://www.planet-x.co'
const canonical = `${siteUrl}/guides/chrome-web-store-listing-checklist`
const title = 'What a Chrome Web Store Listing Actually Needs'
const description = 'A practical guide to Chrome extension listing copy, screenshots, permissions, privacy, reviewer context, and post-publication verification.'
const image = `${siteUrl}/opengraph-image`
const organization = { '@type': 'Organization', name: 'planet.X', url: siteUrl, logo: `${siteUrl}/brand/planet-x-wordmark-transparent.png` }
export const metadata: Metadata = { title: { absolute: `${title} | planet.X` }, description, alternates: { canonical }, openGraph: { title, description, url: canonical, siteName: 'planet.X', type: 'article', images: ['/opengraph-image'] }, twitter: { card: 'summary_large_image', title, description, images: ['/opengraph-image'] } }
const articleSchema = { '@context': 'https://schema.org', '@type': 'Article', headline: title, description, image, datePublished: '2026-09-15', dateModified: '2026-09-15', mainEntityOfPage: canonical, author: organization, publisher: organization }
const points = [
  ['A name that says what the extension does', 'Keep the branded name, but pair it with a functional description. “SessionGrid X — Tab & Workspace Manager” is easier to understand than a mysterious product name alone.'],
  ['A short description with one concrete outcome', 'The first line should explain the job: save and restore workspaces, keep credentials encrypted, capture tabs, or whatever the core behavior is.'],
  ['Real screenshots with readable callouts', 'Show the interface people will actually install. One screenshot should communicate one feature or outcome, not ten tiny panels competing for attention.'],
  ['Permission and privacy consistency', 'The manifest, store privacy answers, privacy policy, and listing copy must tell the same story about what the extension can access and what leaves the device.'],
  ['A release-ready ZIP', 'The exact ZIP submitted should be tested in a clean Chrome profile. manifest.json belongs at the archive root and private development files do not belong in the upload.'],
  ['Reviewer context for non-obvious flows', 'If setup, licensing, side-panel behavior, or another step is not obvious, write reviewer notes that reach the feature without guessing.'],
  ['A live-listing verification pass', 'After publication, check the actual Web Store page: title, description, screenshots, privacy link, developer contact, version, and the install button.'],
]
export default function GuidePage() { return <div className="min-h-screen bg-[#030305] text-white"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} /><StorePageTracker event="article_view" properties={{ article_id: 'chrome-web-store-listing-checklist', article_title: title }} /><SiteHeader /><main><article className="mx-auto max-w-3xl px-5 py-14 sm:px-8"><nav className="font-mono text-[10px] tracking-[.13em] text-white/40 uppercase"><Link href="/guides" className="hover:text-white">Guides</Link> / Chrome Web Store</nav><p className="mt-9 font-mono text-[10px] font-bold tracking-[.16em] text-cyan-300 uppercase">Chrome extension release</p><h1 className="mt-3 text-4xl font-bold tracking-[-.045em] sm:text-5xl">{title}</h1><p className="mt-5 text-base leading-7 text-white/60">A Chrome Web Store listing is part product page, part compliance surface, and part release artifact. The useful version is not a pile of adjectives. It lets a visitor — and a reviewer — answer what the extension does, what it can access, what it looks like, and whether the published build matches the promise.</p><div className="mt-10 grid gap-8">{points.map(([heading, body]) => <section key={heading}><h2 className="flex items-start gap-3 text-2xl font-bold"><Check className="mt-1 size-5 shrink-0 text-primary" aria-hidden="true" />{heading}</h2><p className="mt-3 text-sm leading-7 text-white/58">{body}</p></section>)}</div><section className="mt-12 rounded-2xl border border-cyan-300/20 bg-cyan-300/[.04] p-6"><h2 className="text-2xl font-bold">Use the free release checklist</h2><p className="mt-3 text-sm leading-6 text-white/55">The reusable Markdown checklist covers package structure, permissions, privacy, screenshots, clean-profile QA, reviewer notes, and release evidence.</p><Link href="/store/free/indie-extension-release-checklist" className="mt-5 inline-block font-mono text-[10px] font-bold tracking-[.12em] text-cyan-300 uppercase">Open Indie Extension Release Checklist →</Link></section><section className="mt-12 border-t border-white/10 pt-8"><h2 className="text-xl font-bold">Related planet.X software</h2><div className="mt-4 flex flex-wrap gap-3"><Link href="/store/software/sessiongrid-x" className="rounded-lg border border-white/10 px-4 py-3 text-sm hover:border-cyan-300/35">SessionGrid X</Link><Link href="/store/software/context" className="rounded-lg border border-white/10 px-4 py-3 text-sm hover:border-cyan-300/35">conteXt</Link></div></section></article></main><SiteFooter /></div> }
