type AppResponse={statusCode:number;body:unknown;headers?:Record<string,string>};
const json=(body:unknown,statusCode=200):AppResponse=>({statusCode,body,headers:{'Content-Type':'application/json'}});
const error=(message:string,statusCode=500)=>json({error:message},statusCode);
type RouteHandler=(context:any)=>Promise<AppResponse>|AppResponse;
const router=(routes:Record<string,RouteHandler[]>)=>async(req:any,res:any)=>{
  const routeValue=Array.isArray(req.query?.route)?req.query.route.join('/'):req.query?.route;
  const pathname=routeValue?('/api/'+String(routeValue).replace(/^\/+/,'')):new URL(req.url||'/','http://localhost').pathname;
  const handlers=routes[`${req.method} ${pathname}`];
  if(!handlers)return res.status(404).json({error:'Not found'});
  try{
    const response=await handlers[0]({body:req.body,event:{headers:req.headers||{}},query:req.query||{}});
    for(const [key,value] of Object.entries(response.headers||{}))res.setHeader(key,value);
    return res.status(response.statusCode).json(response.body);
  }catch(cause){
    console.error('Command Center API failure.',cause);
    return res.status(500).json({error:'Internal server error'});
  }
};

const EXTERNAL_INGEST='https://lufvkrnwqbqdaqcgljxt.supabase.co/functions/v1/planetx-analytics-ingest';
const KEY_NAME='PLANETX_ANALYTICS_INGEST_KEY';
const GOOGLE_NAME='GOOGLE_INSIGHTS_CONFIG';
const HEADER='x-planetx-analytics-key';
const str=(value:unknown,max=256)=>String(value??'').slice(0,max);
const originOf=(event:any)=>str(event?.headers?.origin||event?.headers?.Origin,300);
function corsHeaders(origin:string){const allowed=origin==='https://planet-x.co'||origin==='https://www.planet-x.co'?origin:'https://planet-x.co';return{'Access-Control-Allow-Origin':allowed,'Access-Control-Allow-Headers':'Content-Type, X-PlanetX-Analytics-Key','Access-Control-Allow-Methods':'POST, OPTIONS',Vary:'Origin'}}
function withCors(response:ReturnType<typeof json>,origin:string){response.headers={...response.headers,...corsHeaders(origin)};return response}
async function ingestKey(){return process.env[KEY_NAME]||null}
function incomingKey(event:any){const headers=event?.headers||{};return str(headers[HEADER]||headers['X-PlanetX-Analytics-Key'],512)}
function windowQuery(query:Record<string,string>){const params=new URLSearchParams();if(query.from)params.set('from',str(query.from,64));if(query.to)params.set('to',str(query.to,64));const suffix=params.toString();return suffix?`&${suffix}`:''}
async function sharedSummary(sourceProduct:string,query:Record<string,string>){try{const response=await fetch(`${EXTERNAL_INGEST}?mode=summary&source_product=${encodeURIComponent(sourceProduct)}${windowQuery(query)}`,{headers:{Accept:'application/json'},cache:'no-store'});const payload=await response.json().catch(()=>null);if(!response.ok||!payload||typeof payload!=='object')return error(`Shared ${sourceProduct} analytics returned ${response.status}.`,502);return json(payload)}catch(cause){console.error(`Shared ${sourceProduct} analytics failed.`,cause);return error(`Shared ${sourceProduct} analytics are currently unavailable.`,502)}}

const APP_SOURCES=['voice-studio-x','studyhive','bdxm','project-x','xfactor-os'] as const;
async function appSummaries(query:Record<string,string>){const apps=await Promise.all(APP_SOURCES.map(async source=>{try{const response=await fetch(`${EXTERNAL_INGEST}?mode=summary&source_product=${encodeURIComponent(source)}${windowQuery(query)}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error(String(response.status));return await response.json()}catch{return{source,status:'error',total:0,traffic:{visitors:0,sessions:0,pageViews:0,topPages:[],platforms:[]},events:[],trend:[],pulse:[]}}}));return json({apps,fetchedAt:new Date().toISOString()})}

type GoogleConfig={client_email:string;private_key:string;search_console_site_url?:string;analytics_property_id?:string};
const enc=(value:string)=>new TextEncoder().encode(value);
function b64url(value:string|Uint8Array){const bytes=typeof value==='string'?enc(value):value;let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function googleConfig():Promise<GoogleConfig|null>{const raw=process.env[GOOGLE_NAME];if(!raw)return null;try{const parsed=JSON.parse(raw) as GoogleConfig;if(!parsed.client_email||!parsed.private_key)return null;return parsed}catch{return null}}
async function googleToken(config:GoogleConfig){const now=Math.floor(Date.now()/1000);const header=b64url(JSON.stringify({alg:'RS256',typ:'JWT'}));const payload=b64url(JSON.stringify({iss:config.client_email,scope:'https://www.googleapis.com/auth/webmasters.readonly https://www.googleapis.com/auth/analytics.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const pem=config.private_key.replace(/\\n/g,'\n').replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,'');const der=Uint8Array.from(atob(pem),char=>char.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',der,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,enc(`${header}.${payload}`));const assertion=`${header}.${payload}.${b64url(new Uint8Array(signature))}`;const body=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion});const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!response.ok)throw new Error('Google authorization failed');const token=await response.json() as {access_token?:string};if(!token.access_token)throw new Error('Google authorization returned no token');return token.access_token}
const isoDate=(date:Date)=>date.toISOString().slice(0,10);
function dateRange(days:number,lag=0){const end=new Date();end.setUTCDate(end.getUTCDate()-lag);const start=new Date(end);start.setUTCDate(start.getUTCDate()-days+1);return{startDate:isoDate(start),endDate:isoDate(end)}}
async function googleJson(url:string,token:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Google API returned ${response.status}`);return payload as any}
async function googleOverview(){const config=await googleConfig();if(!config)return{status:'setup_required',configured:false,searchConsole:{status:'setup_required'},analytics:{status:'setup_required'}};let token:string;try{token=await googleToken(config)}catch{return{status:'error',configured:true,searchConsole:{status:'error'},analytics:{status:'error'},message:'Google credentials could not be authorized.'}}const search:any={status:config.search_console_site_url?'loading':'setup_required'};const analytics:any={status:config.analytics_property_id?'loading':'setup_required'};const tasks:Promise<void>[]=[];
  if(config.search_console_site_url){tasks.push((async()=>{try{const range=dateRange(28,2);const endpoint=`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(config.search_console_site_url!)}/searchAnalytics/query`;const[daily,queries,pages]=await Promise.all([googleJson(endpoint,token,{...range,dimensions:['date'],rowLimit:100}),googleJson(endpoint,token,{...range,dimensions:['query'],rowLimit:8}),googleJson(endpoint,token,{...range,dimensions:['page'],rowLimit:8})]);const rows=daily.rows||[];search.status='connected';search.totals=rows.reduce((a:any,r:any)=>({clicks:a.clicks+(r.clicks||0),impressions:a.impressions+(r.impressions||0),positionSum:a.positionSum+(r.position||0)*(r.impressions||0)}),{clicks:0,impressions:0,positionSum:0});search.totals.ctr=search.totals.impressions?Math.round(search.totals.clicks/search.totals.impressions*1000)/10:0;search.totals.position=search.totals.impressions?Math.round(search.totals.positionSum/search.totals.impressions*10)/10:0;delete search.totals.positionSum;search.trend=rows.map((r:any)=>({date:r.keys?.[0]||'',clicks:r.clicks||0,impressions:r.impressions||0,ctr:Math.round((r.ctr||0)*1000)/10,position:Math.round((r.position||0)*10)/10}));search.queries=(queries.rows||[]).map((r:any)=>({label:r.keys?.[0]||'Unknown query',clicks:r.clicks||0,impressions:r.impressions||0}));search.pages=(pages.rows||[]).map((r:any)=>({label:String(r.keys?.[0]||'').replace(/^https?:\/\/[^/]+/,'')||'/',clicks:r.clicks||0,impressions:r.impressions||0}));const inspectionUrls=(pages.rows||[]).map((r:any)=>String(r.keys?.[0]||'')).filter((url:string)=>/^https?:\/\//.test(url)).slice(0,5);search.indexing=await Promise.all(inspectionUrls.map(async(inspectionUrl:string)=>{try{const result=await googleJson('https://searchconsole.googleapis.com/v1/urlInspection/index:inspect',token,{inspectionUrl,siteUrl:config.search_console_site_url,languageCode:'en-US'});const status=result.inspectionResult?.indexStatusResult||{};return{url:inspectionUrl,verdict:status.verdict||'VERDICT_UNSPECIFIED',coverageState:status.coverageState||'Unknown',indexingState:status.indexingState||'Unknown',pageFetchState:status.pageFetchState||'Unknown',robotsTxtState:status.robotsTxtState||'Unknown',lastCrawlTime:status.lastCrawlTime||null,googleCanonical:status.googleCanonical||null,userCanonical:status.userCanonical||null}}catch{return{url:inspectionUrl,verdict:'ERROR',coverageState:'Inspection unavailable'}}}))}catch{search.status='error';search.message='Search Console is configured but unavailable.'}})())}
  if(config.analytics_property_id){tasks.push((async()=>{try{const range={startDate:'28daysAgo',endDate:'today'};const endpoint=`https://analyticsdata.googleapis.com/v1beta/properties/${encodeURIComponent(config.analytics_property_id!)}:runReport`;const[summary,daily,channels]=await Promise.all([googleJson(endpoint,token,{dateRanges:[range],metrics:[{name:'activeUsers'},{name:'sessions'},{name:'screenPageViews'},{name:'eventCount'},{name:'totalRevenue'}]}),googleJson(endpoint,token,{dateRanges:[range],dimensions:[{name:'date'}],metrics:[{name:'activeUsers'},{name:'sessions'}],orderBys:[{dimension:{dimensionName:'date'}}],limit:'40'}),googleJson(endpoint,token,{dateRanges:[range],dimensions:[{name:'sessionDefaultChannelGroup'}],metrics:[{name:'sessions'}],orderBys:[{metric:{metricName:'sessions'},desc:true}],limit:'8'})]);const values=summary.rows?.[0]?.metricValues||[];analytics.status='connected';analytics.totals={activeUsers:Number(values[0]?.value||0),sessions:Number(values[1]?.value||0),pageViews:Number(values[2]?.value||0),events:Number(values[3]?.value||0),revenue:Number(values[4]?.value||0)};analytics.trend=(daily.rows||[]).map((r:any)=>({date:r.dimensionValues?.[0]?.value||'',users:Number(r.metricValues?.[0]?.value||0),sessions:Number(r.metricValues?.[1]?.value||0)}));analytics.channels=(channels.rows||[]).map((r:any)=>({label:r.dimensionValues?.[0]?.value||'Unassigned',value:Number(r.metricValues?.[0]?.value||0)}))}catch{analytics.status='error';analytics.message='Google Analytics is configured but unavailable.'}})())}
  await Promise.all(tasks);return{status:search.status==='connected'||analytics.status==='connected'?'connected':search.status==='error'||analytics.status==='error'?'error':'setup_required',configured:true,searchConsole:search,analytics,fetchedAt:new Date().toISOString()}}

export default router({
  'GET /api/_healthcheck':[async()=>json({message:'Success',analyticsSummary:'shared-ledger',commandCenter:'v2'})],
  'OPTIONS /api/events':[async({event})=>withCors(json({ok:true}),originOf(event))],
  'GET /api/events/authorize':[async({event})=>{const expected=await ingestKey();if(!expected)return error('Analytics ingestion key is not configured.',503);if(incomingKey(event)!==expected)return error('Unauthorized.',401);return json({ok:true})}],
  'GET /api/events/config':[async()=>json({endpoint:EXTERNAL_INGEST,header:'X-PlanetX-Analytics-Key',schema:['event','timestamp','source_product','source_surface','session_id','anonymous_user_id','path','platform','properties'],configured:true,summaryAccess:'aggregate-only',commandCenterKeyAuthority:Boolean(process.env[KEY_NAME]),googleInsights:Boolean(process.env[GOOGLE_NAME])})],
  'POST /api/events':[async({body,event})=>{const origin=originOf(event);const expected=await ingestKey();if(!expected)return withCors(error('Use the shared analytics edge endpoint.',503),origin);if(incomingKey(event)!==expected)return withCors(error('Unauthorized.',401),origin);try{const response=await fetch(EXTERNAL_INGEST,{method:'POST',headers:{'Content-Type':'application/json','X-PlanetX-Analytics-Key':expected},body:JSON.stringify(body??{})});const payload=await response.json().catch(()=>({error:'Shared analytics returned an invalid response.'}));return withCors(json(payload,response.status),origin)}catch(cause){console.error('Shared analytics write failed.',cause);return withCors(error('Shared analytics write failed.',502),origin)}}],
  'GET /api/analytics/website':[async({query})=>sharedSummary('planet-x.co',query)],
  'GET /api/products/visualx/analytics':[async({query})=>sharedSummary('visual-x',query)],
  'GET /api/apps/analytics':[async({query})=>appSummaries(query)],
  'GET /api/google/overview':[async()=>json(await googleOverview())],
});
