const TOKEN_NAME='METRICOOL_USER_TOKEN';
const BLOG_ID=process.env.METRICOOL_BLOG_ID||'6864248';
const BASE='https://app.metricool.com';
const json=(res:any,status:number,body:unknown)=>res.status(status).json(body);
const num=(v:unknown)=>Number(v||0);
const iso=(d:Date)=>d.toISOString().slice(0,10).replace(/-/g,'');
const CONNECTIONS={pinterest:{connected:true,handle:'planetXfactor'},facebook:{connected:true,handle:'planet.X'},instagram:{connected:true,handle:'xfactor_planet_x'},linkedin:{connected:true,handle:'planet.X'},youtube:{connected:true,handle:'planet.X'},tiktok:{connected:false,handle:null}} as const;

type Network='pinterest'|'facebook'|'instagram'|'linkedin'|'youtube'|'tiktok';
type Spec={evolution:string[];posts:string[];reels?:string[]};
const SPECS:Record<Network,Spec>={
 pinterest:{evolution:['PIEV01','PIEV04','PIEV05','PIEV06','PIEV07','PIEV09','PIEV10','PIEV9998'],posts:['PIPO03','PIPO07','PIPO08','PIPO09','PIPO10','PIPO11']},
 facebook:{evolution:['FBEV03','FBEV10','FBEV12','FBEV16','FBEV17','FBEV47','FBEV49'],posts:['FBPO03','FBPO06','FBPO08','FBPO09','FBPO11','FBPO12','FBPO13','FBPO14']},
 instagram:{evolution:['IGEV01','IGEV05','IGEV06','IGEV09','IGEV22','IGEV23','IGEV25','IGEV42','IGEV43'],posts:['IGPO03','IGPO06','IGPO12','IGPO13','IGPO14','IGPO15','IGPO27','IGPO28'],reels:['IGRE03','IGRE06','IGRE09','IGRE10','IGRE11','IGRE12','IGRE21','IGRE23','IGRE24','IGRE27']},
 linkedin:{evolution:['LIEV01','LIEV04','LIEV05','LIEV06','LIEV07','LIEV08','LIEV10','LIEV18','LIEV19'],posts:['LIPO03','LIPO04','LIPO08','LIPO09','LIPO10','LIPO12','LIPO13','LIPO18']},
 youtube:{evolution:['YTEV01','YTEV02','YTEV04','YTEV05','YTEV06','YTEV10','YTEV12','YTEV13','YTEV19'],posts:['YTVP17','YTVP05','YTVP06','YTVP07','YTVP08','YTVP09','YTVP11','YTVP12']},
 tiktok:{evolution:['TKEV01','TKEV02','TKEV03','TKEV04','TKEV05','TKEV06','TKEV07','TKEV09','TKEV11'],posts:['TKPO05','TKPO03','TKPO07','TKPO08','TKPO09','TKPO10','TKPO11','TKPO13','TKPO15']},
};
const LABELS:Record<string,string>={
 PIEV01:'impressions',PIEV04:'interactions',PIEV05:'pinClicks',PIEV06:'outboundClicks',PIEV07:'saves',PIEV09:'followers',PIEV10:'followersDelta',PIEV9998:'engagement',PIPO03:'title',PIPO07:'url',PIPO08:'impressions',PIPO09:'saves',PIPO10:'pinClicks',PIPO11:'outboundClicks',
 FBEV03:'pageViews',FBEV10:'interactions',FBEV12:'impressions',FBEV16:'clicks',FBEV17:'followers',FBEV47:'followersGained',FBEV49:'mediaViews',FBPO03:'content',FBPO06:'url',FBPO08:'comments',FBPO09:'linkClicks',FBPO11:'impressions',FBPO12:'reach',FBPO13:'reactions',FBPO14:'shares',
 IGEV01:'followers',IGEV05:'views',IGEV06:'reach',IGEV09:'interactions',IGEV22:'reels',IGEV23:'reelViews',IGEV25:'reelInteractions',IGEV42:'accountsEngaged',IGEV43:'followersGained',IGPO03:'content',IGPO06:'url',IGPO12:'interactions',IGPO13:'likes',IGPO14:'reach',IGPO15:'saves',IGPO27:'shares',IGPO28:'views',IGRE03:'content',IGRE06:'url',IGRE09:'interactions',IGRE10:'likes',IGRE11:'reach',IGRE12:'saves',IGRE21:'shares',IGRE23:'views',IGRE24:'avgWatchTime',IGRE27:'retention',
 LIEV01:'followers',LIEV04:'posts',LIEV05:'likes',LIEV06:'comments',LIEV07:'clicks',LIEV08:'followersGained',LIEV10:'interactions',LIEV18:'impressions',LIEV19:'shares',LIPO03:'title',LIPO04:'content',LIPO08:'url',LIPO09:'clicks',LIPO10:'comments',LIPO12:'impressions',LIPO13:'reactions',LIPO18:'shares',
 YTEV01:'followers',YTEV02:'views',YTEV04:'videos',YTEV05:'followersGained',YTEV06:'followersLost',YTEV10:'likes',YTEV12:'comments',YTEV13:'publishedViews',YTEV19:'shares',YTVP17:'title',YTVP05:'url',YTVP06:'views',YTVP07:'watchMinutes',YTVP08:'avgWatchTime',YTVP09:'likes',YTVP11:'comments',YTVP12:'shares',
 TKEV01:'videos',TKEV02:'views',TKEV03:'likes',TKEV04:'comments',TKEV05:'shares',TKEV06:'interactions',TKEV07:'followers',TKEV09:'profileViews',TKEV11:'reach',TKPO05:'content',TKPO03:'url',TKPO07:'views',TKPO08:'likes',TKPO09:'comments',TKPO10:'shares',TKPO11:'reach',TKPO13:'fullWatchRate',TKPO15:'avgWatchTime',
};
function range(value:unknown){const key=String(value||'30d').toLowerCase();const days=key==='24h'?2:key==='7d'?7:key==='90d'?90:30;const end=new Date();const start=new Date(end);start.setUTCDate(start.getUTCDate()-days+1);return{key,start:iso(start),end:iso(end)}}
function auth(token:string){return token.split('.').length===3?{Authorization:`Bearer ${token}`}:{'X-Mc-Auth':token}}
async function dataset(token:string,fields:string[],start:string,end:string,withDate=false){const ids=[...fields,...(withDate?['evdate']:[])];const params=new URLSearchParams({start,end,blogId:BLOG_ID,userToken:token,fields:ids.join(','),integrationSource:'MCP'});const response=await fetch(`${BASE}/api/datastudio/datasets?${params}`,{headers:{...auth(token),Accept:'application/json'},cache:'no-store'});if(!response.ok)throw new Error(`Metricool returned ${response.status}`);const rows=await response.json();return Array.isArray(rows)?rows:[]}
function objectify(rows:any[],fields:string[],withDate=false){return rows.map(row=>{const out:any={};fields.forEach((field,i)=>{if(row?.[i]!==null&&row?.[i]!==undefined)out[LABELS[field]||field]=row[i]});if(withDate&&row?.[fields.length])out.date=String(row[fields.length]);return out})}
function sum(rows:any[],key:string){return rows.reduce((a,row)=>a+num(row[key]),0)}
function last(rows:any[],key:string){for(let i=rows.length-1;i>=0;i--){if(rows[i][key]!==undefined&&rows[i][key]!==null)return num(rows[i][key])}return 0}
function summary(network:Network,rows:any[]){
 if(network==='pinterest')return{impressions:sum(rows,'impressions'),interactions:sum(rows,'interactions'),clicks:sum(rows,'pinClicks'),outboundClicks:sum(rows,'outboundClicks'),saves:sum(rows,'saves'),followers:last(rows,'followers'),followersGained:sum(rows,'followersDelta'),engagement:last(rows,'engagement')};
 if(network==='facebook')return{impressions:sum(rows,'impressions'),views:sum(rows,'pageViews')+sum(rows,'mediaViews'),interactions:sum(rows,'interactions'),clicks:sum(rows,'clicks'),followers:last(rows,'followers'),followersGained:sum(rows,'followersGained')};
 if(network==='instagram')return{views:sum(rows,'views'),reach:sum(rows,'reach'),interactions:sum(rows,'interactions'),followers:last(rows,'followers'),followersGained:sum(rows,'followersGained'),reels:sum(rows,'reels'),reelViews:sum(rows,'reelViews'),reelInteractions:sum(rows,'reelInteractions'),accountsEngaged:sum(rows,'accountsEngaged')};
 if(network==='linkedin')return{impressions:sum(rows,'impressions'),interactions:sum(rows,'interactions'),clicks:sum(rows,'clicks'),likes:sum(rows,'likes'),comments:sum(rows,'comments'),shares:sum(rows,'shares'),followers:last(rows,'followers'),followersGained:sum(rows,'followersGained'),posts:sum(rows,'posts')};
 if(network==='youtube')return{views:sum(rows,'views'),publishedViews:sum(rows,'publishedViews'),likes:sum(rows,'likes'),comments:sum(rows,'comments'),shares:sum(rows,'shares'),followers:last(rows,'followers'),followersGained:sum(rows,'followersGained'),followersLost:sum(rows,'followersLost'),videos:sum(rows,'videos')};
 return{views:sum(rows,'views'),reach:sum(rows,'reach'),interactions:sum(rows,'interactions'),likes:sum(rows,'likes'),comments:sum(rows,'comments'),shares:sum(rows,'shares'),followers:last(rows,'followers'),profileViews:sum(rows,'profileViews'),videos:sum(rows,'videos')};
}
function contentScore(item:any){return num(item.views)+num(item.impressions)+num(item.reach)+num(item.interactions)*4+num(item.likes)*3+num(item.comments)*4+num(item.saves)*5+num(item.shares)*5+num(item.clicks)*5+num(item.linkClicks)*5+num(item.outboundClicks)*6+num(item.watchMinutes)}
async function readNetwork(network:Network,token:string,start:string,end:string){if(network==='tiktok'&&!CONNECTIONS.tiktok.connected)return{network,status:'setup_required',connected:false,handle:null,summary:{},trend:[],content:[]};const spec=SPECS[network];try{const [evRaw,postRaw,reelRaw]=await Promise.all([dataset(token,spec.evolution,start,end,true),dataset(token,spec.posts,start,end,false),spec.reels?dataset(token,spec.reels,start,end,false):Promise.resolve([])]);const trend=objectify(evRaw,spec.evolution,true);const posts=objectify(postRaw,spec.posts);const reels=spec.reels?objectify(reelRaw,spec.reels):[];const content=[...posts.map(x=>({...x,type:'post'})),...reels.map(x=>({...x,type:'reel'}))].sort((a,b)=>contentScore(b)-contentScore(a)).slice(0,25);return{network,status:'connected',connected:true,handle:CONNECTIONS[network].handle,summary:summary(network,trend),trend,content}}catch(cause){console.error(`Metricool ${network} read failed.`,cause);return{network,status:'error',connected:true,handle:CONNECTIONS[network].handle,summary:{},trend:[],content:[],message:cause instanceof Error?cause.message:'Provider read failed'}}}

export default async function handler(req:any,res:any){
 if(req.method!=='GET')return json(res,405,{error:'Method not allowed'});const token=process.env[TOKEN_NAME];const r=range(req.query?.range);const requested=String(req.query?.network||'all').toLowerCase();const all=(['pinterest','facebook','instagram','linkedin','youtube','tiktok'] as Network[]);const selected=requested==='all'?all:all.includes(requested as Network)?[requested as Network]:all;
 if(!token)return json(res,200,{status:'setup_required',configured:false,provider:'Metricool',brandId:BLOG_ID,range:r.key,fetchedAt:new Date().toISOString(),connections:CONNECTIONS,message:'Native social analytics are ready but need METRICOOL_USER_TOKEN in the Command Center server environment. TikTok also needs to be connected in Metricool.',networks:Object.entries(CONNECTIONS).filter(([network])=>selected.includes(network as Network)).map(([network,value])=>({network,status:value.connected?'credential_required':'setup_required',...value}))});
 const networks=await Promise.all(selected.map(network=>readNetwork(network,token,r.start,r.end)));const connected=networks.filter(n=>n.status==='connected').length;return json(res,200,{status:connected?'connected':'error',configured:true,provider:'Metricool',brandId:BLOG_ID,range:r.key,fetchedAt:new Date().toISOString(),connections:CONNECTIONS,networks});
}
