import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BookOpen } from 'lucide-react'
import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'

export const metadata: Metadata = { title: { absolute: 'planet.X Guides — Shipping Software, Extensions & Digital Products' }, description: 'Practical planet.X guides based on real software release, Chrome Web Store, product-media, and digital-product workflows.', alternates: { canonical: '/guides' }, openGraph: { title: 'planet.X Guides — Shipping Software, Extensions & Digital Products', description: 'Practical release and product-production guides from planet.X.', url: '/guides', siteName: 'planet.X', type: 'website', images: ['/opengraph-image'] } }
const guides = [
  { href: '/guides/chrome-web-store-listing-checklist', title: 'What a Chrome Web Store listing actually needs', description: 'A practical breakdown of product copy, screenshots, privacy, permissions, reviewer context, and post-publication checks.' },
  { href: '/guides/chrome-extension-screenshot-guide', title: 'How to build 1280×800 Chrome extension screenshots', description: 'A repeatable way to turn real extension UI into readable store screenshots without fake browser chrome or tiny text.' },
]
export default function GuidesPage() { return <div className="min-h-screen bg-[#030305] text-white"><SiteHeader /><main><section className="border-b border-white/10 bg-white/[.018]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="flex items-center gap-2 font-mono text-[10px] font-bold tracking-[.16em] text-cyan-300 uppercase"><BookOpen className="size-4" aria-hidden="true" /> planet.X field notes</div><h1 className="mt-3 max-w-4xl text-4xl font-bold tracking-[-.045em] sm:text-5xl">Guides from the work, not SEO filler.</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/60">Short technical guides built around release work planet.X is actually doing: Chrome extensions, store media, privacy, packaging, local-first software, and digital-product delivery.</p></div></section><section className="mx-auto max-w-6xl px-5 py-12 sm:px-8"><div className="grid gap-5 md:grid-cols-2">{guides.map((guide) => <Link key={guide.href} href={guide.href} className="group rounded-2xl border border-white/10 bg-white/[.025] p-6 hover:border-cyan-300/35"><p className="font-mono text-[9px] tracking-[.14em] text-primary uppercase">Guide</p><h2 className="mt-3 text-2xl font-bold">{guide.title}</h2><p className="mt-3 text-sm leading-6 text-white/55">{guide.description}</p><span className="mt-6 inline-flex items-center gap-2 font-mono text-[10px] font-bold tracking-[.12em] text-cyan-300 uppercase">Read guide <ArrowRight className="size-4" aria-hidden="true" /></span></Link>)}</div></section></main><SiteFooter /></div> }
